version: "3.8"

services:
    user-service:
        build: 
            context: ../services/user-service
        ports:
            - "50051:50051"
            - "8080:8080"
        networks:
            - myapp-network

    course-service:
        build: 
            context: ../services/course-service
        ports:
            - "50052:50052"
        networks:
            - myapp-network

networks:
    myapp-network:
        driver: bridge
