apiVersion: apps/v1
kind: Deployment
metadata:
    name: course-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: course-service
    template:
        metadata:
            labels:
                app: course-service
        spec:
            containers:
                - name: course-service
                  image: amrimuf/course-service:latest
                  ports:
                      - containerPort: 50052
